# Generated by Django 3.0.8 on 2020-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='type',
            field=models.CharField(choices=[('#eee', 'grow'), ('#EA00A3', 'note')], default='grow', max_length=24),
        ),
    ]
