# Generated by Django 3.0.8 on 2020-07-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_image_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.BlogEntry'),
        ),
    ]
